// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace backend.Migrations
{
    [DbContext(typeof(SampleProjContext))]
    [Migration("20210514142706_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Domain.AcademicHistory", b =>
                {
                    b.Property<Guid>("AcademicHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<Guid?>("GraduateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("AcademicHistoryId");

                    b.HasIndex("GraduateId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("backend.Domain.Graduate", b =>
                {
                    b.Property<Guid>("GraduateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraduateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GraduateId");

                    b.ToTable("Graduates");
                });

            modelBuilder.Entity("backend.Domain.AcademicHistory", b =>
                {
                    b.HasOne("backend.Domain.Graduate", null)
                        .WithMany("AcademicHistory")
                        .HasForeignKey("GraduateId");
                });

            modelBuilder.Entity("backend.Domain.Graduate", b =>
                {
                    b.Navigation("AcademicHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
